version: '3.8'
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service-1
      - user-service-2
      - user-service-3
    networks:
      - ecomarket-net

  user-service-1:
    build: .
    image: ecomarket-users-service
    container_name: user-service-1
    environment:
      - INSTANCE_ID=1
    command: uvicorn users_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - ecomarket-net

  user-service-2:
    build: .
    image: ecomarket-users-service
    container_name: user-service-2
    environment:
      - INSTANCE_ID=2
    command: uvicorn users_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    networks:
      - ecomarket-net

  user-service-3:
    build: .
    image: ecomarket-users-service
    container_name: user-service-3
    environment:
      - INSTANCE_ID=3
    command: uvicorn users_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
    networks:
      - ecomarket-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecomarket-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ecomarket_user
      RABBITMQ_DEFAULT_PASS: ecomarket_password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - ecomarket-net

networks:
  ecomarket-net:
    driver: bridge