version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecomarket-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ecomarket_user
      RABBITMQ_DEFAULT_PASS: ecomarket_password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - ecomarket-net

  user-service-1:
    build: .
    image: ecomarket-users-service:latest
    container_name: user-service-1
    environment:
      - INSTANCE_ID=1
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    ports:
      - '8000:8000'
    depends_on:
      - rabbitmq
    networks:
      - ecomarket-net
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request as u; resp=u.urlopen('http://127.0.0.1:8000/health'); sys.exit(0 if resp.getcode()==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 3

  user-service-2:
    build: .
    image: ecomarket-users-service:latest
    container_name: user-service-2
    environment:
      - INSTANCE_ID=2
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    ports:
      - '8001:8000'
    depends_on:
      - rabbitmq
    networks:
      - ecomarket-net
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request as u; resp=u.urlopen('http://127.0.0.1:8000/health'); sys.exit(0 if resp.getcode()==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 3

  user-service-3:
    build: .
    image: ecomarket-users-service:latest
    container_name: user-service-3
    environment:
      - INSTANCE_ID=3
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    ports:
      - '8002:8000'
    depends_on:
      - rabbitmq
    networks:
      - ecomarket-net
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request as u; resp=u.urlopen('http://127.0.0.1:8000/health'); sys.exit(0 if resp.getcode()==200 else 1)"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:stable
    container_name: nginx_taller6
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service-1
      - user-service-2
      - user-service-3
    networks:
      - ecomarket-net

networks:
  ecomarket-net:
    driver: bridge